### ISSUE TITLE
Libyui version

### ISSUE THREAD

**Issue by ozky** [xquiet/manatools#1]
Can i build Cauldron manatools against older version libyui6 3.1.4 ? or do i need to build libyui7 from Cauldron ?. 
Mageia 5 manatools is very buggy that's why i wan't to manually backport it to own usage.

**Comment by anaselli** [comment]
yes manatools should work with old libyui version. I can't remember if the spec file is compatible though, you could need to make some changes there. You can also install it from git to verify if all is ok, locally into your home following the read-me instructions:

```
To install this module with local::lib (see perldoc local::lib for details). Note add also -MCPAN if you want to install from cpan locally.

alias perl='perl -Mlocal::lib'
perl Makefile.PL
make
make install

Since manatools works with root privileges you can do the above and install it locally then run tools as root adding your user environment variables, to know which ones run perl -Mlocal::lib as user and execute the output as root.
e.g. as user perl -Mlocal::lib > ~/perl.env
su -
. ~yourusername/perl.env
and then run your tools (manauser for instance)
```

**Comment by anaselli** [comment]
btw which bugs are you talking about? maybe open bug reports into https://bugs.mageia.org/.
It is very important having feedbacks, otherwise ewe cannot fix bugs.

**Comment by ozky** [comment]
Manauser crash everytime i try to start click edit user i added log file.
I try to compile it as i looked our svn web spec file and it only require libyui6 if it's build against it.
https://svnweb.mageia.org/packages/updates/5/manatools/current/SPECS/manatools.spec?revision=826294&view=co

Yes i will report to bugzilla.

One feedback can you add socket5 proxy support to manaproxy ?. Many users use tor and it's only socket5 proxy server,would be ideal to add support because that would allow users to configure it systemwide proxy without configuring manually programs one by one.

[manauser.txt](https://github.com/xquiet/manatools/files/233584/manauser.txt)

**Comment by anaselli** [comment]
The below exception seems to show an empty field into the dialog, but the line 1605 is different here 
so I'm not sure which field is... it could be a problem we have yet, I don't remember i fixed anything there.... Could you please tell me which is the field?

```
Uncaught exception from user code:
        ValueError invalid null reference in method 'YInputField_setValue', argument 2 of type 'std::string const &' at /usr/lib/perl5/vendor_perl/5.20.1/ManaTools/Module/Users.pm line 1605.
        ManaTools::Module::Users::_groupDataTabWidget(ManaTools::Module::Users=HASH(0x1d78b68), yui::YDialog=HASH(0x30a6058), yui::YReplacePoint=HASH(0x30af370), "", undef) called at /usr/lib/perl5/vendor_perl/5.20.1/ManaTools/Module/Users.pm line 2188
        ManaTools::Module::Users::_editGroupDialog(ManaTools::Module::Users=HASH(0x1d78b68)) called at /usr/lib/perl5/vendor_perl/5.20.1/ManaTools/Module/Users.pm line 2253
        ManaTools::Module::Users::_editUserOrGroup(ManaTools::Module::Users=HASH(0x1d78b68)) called at /usr/lib/perl5/vendor_perl/5.20.1/ManaTools/Module/Users.pm line 2544
        ManaTools::Module::Users::_manageUsersDialog(ManaTools::Module::Users=HASH(0x1d78b68)) called at /usr/lib/perl5/vendor_perl/5.20.1/ManaTools/Module/Users.pm line 221
        ManaTools::Module::Users::start(ManaTools::Module::Users=HASH(0x1d78b68)) called at /usr/bin/manauser line 30
<_M_> [ui] YUILoader.cc:104 deleteUI(): Shutting down UI

```

for manaproxy let's see if @xquiet knows what you're asking for :)

**Comment by anaselli** [comment]
mhmm
it seems we don't have a valid group name here IIUC :/ 
`$groupDataWidget{groupname}->setValue($groupData{groupname});`
I could add a secure check there but an username should have a group to which belongs to... or no?
does userdrake work instead?

**Comment by ozky** [comment]
Yes it works  and user and group is created when installed Mageia.

**Comment by anaselli** [comment]
ok i think i could have got it, during the mageia 5 (and 4) developing time we could not compare YItems so i used to compare labels but that could fail for translated strings... I could try to make a patch for a test if you agree. And if it works i would probably work on real fix for cauldron  and thinking for a backport in 5 if you open a bug.

**Comment by ozky** [comment]
Yes make patch and i will test it. I already have lot of experience testing,i was in our qa team over year testing updates.

**Comment by anaselli** [comment]
please test the patch below
https://gist.github.com/anaselli/cff6f566fcc45c5fd2203d0c4ae0e1ed
It should work also into your lib/Module/Users.pm file I think it's not a definitive solution yet, but that should solve most of the problems. Let me know the results :)

**Comment by ozky** [comment]
I try to build it with edited spec file but it fails to apply that patch.
[patch.txt](https://github.com/xquiet/manatools/files/235041/patch.txt)

[manatools.txt](https://github.com/xquiet/manatools/files/235044/manatools.txt)

**Comment by anaselli** [comment]
try this one
https://gist.github.com/anaselli/cff6f566fcc45c5fd2203d0c4ae0e1ed#file-manauser_tab_items-patch

**Comment by ozky** [comment]
I got it compiled but it still crash this time some perl errors.
Log is taken from normal user,root not crash when start from terminal but start from gui it will crash.
[log.txt](https://github.com/xquiet/manatools/files/235227/log.txt)

**Comment by anaselli** [comment]
Sorry i seem i have missed at least one more : (
use also this [additional patch](https://gist.github.com/anaselli/cff6f566fcc45c5fd2203d0c4ae0e1ed#file-manauser_users_tab_items-patch)

**Comment by ozky** [comment]
Same errors again.

**Comment by anaselli** [comment]
same? Unfortunately i don't have that problem so it's hard to me to debug it :(

**Comment by ozky** [comment]
Yes but have you tested only Cauldron version ? it's not having that problem.

**Comment by anaselli** [comment]
Cauldron should have added translations, I'm in mga5, but i updated libyui and rebuilt all against it.
I'm not sure it is related to libyui though so if you want to try new manatools you can i think you must change yui_major   to 6 and add back userdrake instead of USER as dependencies and see if it solved... of course if it is related to strings... it could happen again if not to you to other users... In any case thanks for the feed back

**Comment by ozky** [comment]
I can just build it from Cauldron that's ok for me. 
And for feedback i always wan't to give it makes this distro even more better.

**Comment by anaselli** [comment]
:+1: let me know how's going on in that way then. I will close this issue later eventually.

**Comment by ozky** [comment]
Yes it's working you can close this bug,

**Comment by anaselli** [comment]
thanks
