### ISSUE TITLE
Manatools locale problem

### ISSUE THREAD

**Issue by ozky** [xquiet/manatools#2]
I found weird language side problem as my last name use ä and now it looks like this.
`Otto LeipÃ¤lÃ¤`
Here is screenshot. 
![mpan](https://cloud.githubusercontent.com/assets/1551665/14887395/5351b822-0d5e-11e6-9d40-593664f4b567.png)
I found too that all desktop files have quite intresting way to add icon with specify exact locale why ?.
`Icon[eu]=/usr/share/icons/mpan.png`
 icon are not releated to locale so would be more better to keep it more cleaner and use only. `Icon=/usr/share/icons/mpan.png`

**Comment by anaselli** [comment]
Il 28/04/2016 15:38, Otto Leipälä ha scritto:

> I found weird language side problem as my last name use ä and now it
> looks like this.
> |Otto LeipÃ¤lÃ¤|
> odd all should be UTF-8 will check it...
> 
> I found too that all desktop files have quite intresting way to add icon
> with specify exact locale why ?.
> |Icon[eu]=/usr/share/icons/mpan.png|
> icon are not releated to locale so would be more better to keep it more
> cleaner and use only. |Icon=/usr/share/icons/mpan.png|

That at last, has been wanted, we decided it in accord to the
translation team that could be of help in some cases, leaving the
opportunities to use localized icons.
From my point of view was easier to leave it than to remove it :)

**Comment by ozky** [comment]
Yeah you need to press too many times backspace to remove them. :)

**Comment by anaselli** [comment]
Seems to be ok here
![manauser](https://cloud.githubusercontent.com/assets/1303486/14899892/7b0e4864-0d8e-11e6-9b77-a2cdb307dbe7.png)

**Comment by ozky** [comment]
It's getting more and more weird problem.

**Comment by anaselli** [comment]
Could you please check if your /etc/passwd is in UTF-8?

**Comment by ozky** [comment]
Yeah it's utf-8.

**Comment by anaselli** [comment]
just out of curiosity,  I was trying to reproduce the problem and i found a way to,
so if you add a new user with special chars have you that problem? (i didn't reproduce that)
If not then i think you edited the user and clicked ok (even without changes) then chars are changed (reproduced).

**Comment by anaselli** [comment]
could you please test this [patch?](https://github.com/xquiet/manatools/commit/7e3b48905ba456d46c64abe314fdc8393bf202e3)

**Comment by ozky** [comment]
Yes i edited user and click ok i also added it to vbox user group.
Patch is working and seems you already build it to Cauldron you can close issue.

**Comment by ozky** [comment]
I installed Mga6 dev1 and get manauser crash everytime i try to add user to any group.
`Uncaught exception from user code:
        User could not be modified: 'Invalid contents of lock /etc/shadow.lock'
        ManaTools::Shared::Users::modifyUser(ManaTools::Shared::Users=HASH(0x5f1bdd0), HASH(0x65dfcb8)) called at /usr/lib/perl5/vendor_perl/5.22.1/ManaTools/Module/Users.pm line 1999
        ManaTools::Module::Users::_userEdit_Ok(ManaTools::Module::Users=HASH(0x3f01178), HASH(0x63c4cf0)) called at /usr/lib/perl5/vendor_perl/5.22.1/ManaTools/Module/Users.pm line 2136
        ManaTools::Module::Users::_editUserDialog(ManaTools::Module::Users=HASH(0x3f01178)) called at /usr/lib/perl5/vendor_perl/5.22.1/ManaTools/Module/Users.pm line 2307
        ManaTools::Module::Users::_editUserOrGroup(ManaTools::Module::Users=HASH(0x3f01178)) called at /usr/lib/perl5/vendor_perl/5.22.1/ManaTools/Module/Users.pm line 2622
        ManaTools::Module::Users::_manageUsersDialog(ManaTools::Module::Users=HASH(0x3f01178)) called at /usr/lib/perl5/vendor_perl/5.22.1/ManaTools/Module/Users.pm line 280
        ManaTools::Module::Users::start(ManaTools::Module::Users=HASH(0x3f01178)) called at /usr/bin/mpan line 87
<_M_> [ui] YUILoader.cc:104 deleteUI(): Shutting down UI
<ERR> [ui] YUI.cc:94 ~YUI(): 2 open dialogs left over`
[mpan.txt](https://github.com/xquiet/manatools/files/248635/mpan.txt)

**Comment by ozky** [comment]
Seems to releated to this Mga6 bug.
https://bugs.mageia.org/show_bug.cgi?id=18301
http://svnweb.mageia.org/packages?view=revision&revision=1009231

**Comment by anaselli** [comment]
Please open another issue I cannot follow the comments in this way :(
Or open it in mageia bugzilla.
I didn't understand what you got...

**Comment by ozky** [comment]
Sorry i removed my post cause of that and added them to that new bug.
