### ISSUE TITLE
just a question.. dnfsamba

### ISSUE THREAD

**Issue by blackcrack** [xquiet/manatools#6]
According this :
https://github.com/manatools/dnfdragora/issues/111#issuecomment-405008041

Hi Peoples,

i guess you know from where i am.. how ever, a dnfsamba could be very cool, in the view of setup-samba which it's gone since Fedora 25, it is maybe possible for create a dnfsamba like in d-tools ?
because this works wonderful and should also usable in other distros where manatools use.. i might maybe against the manatools in OMLx because the D-tools should stay and maybe reprogrammed and update in an other p-lang, which was do .. but i must admit, the manatools be really pretty well so far .. would really good if be a dnfsamba also on it.
At OMLx , the urpmi and Draktools should be maintained , also if be reprogrammed in an other language
and a urpmi for rpm4 exist.. so the sourcecode, why not use this.. okey, this is the wrong place to write this.. a distro with a history should not mixed up.. and diluted with other/ foreign tools
because it be not hold at the type of the Distro .. how ever ../ thinking out loud \...

Actually, I just started because of dnfsamba so, could be dnfsamba be an issue/internal project at the manatools ? would be really great because then have the Admins/Users of the Distro again a really well Gui for configuring Samba Server and the SambaUsers(copy from system with UID/GID{button}) with the Samba folders and the access to it.

best regards
Blacky

blackysgate.de/net

**Comment by anaselli** [comment]
honestly i didn't get what you asked for :)
Are you asking for a new samba configuration tool in manatools, to use an existing samba configuration tool in manatools, or to port an existing one into?
Last could be interesting, but we need to have references.
BTW python-manatools has not been released yet, and perl one has not been imported in fedora by fedora people.

**Comment by blackcrack** [comment]
Yes, a new Samba-configurations tool, like them of Draktools , this it is maybe possible to porting into manatools. To have a possible for all distro's who have manatools included, configuring Samba with gui in a easy way.
Fedora have included manatools and OpenMandriva want included too for 4.0 so it is no difference which distribution i use .. (as sidekick info {they pull themselves away the floor , they want discontinue urpmi and want include manatools, they kill the distribution softly because they want no more maintaining urpmi and draktools .. so .. imho.. kick off OMLx it is no more what it should be}) so would it the best way if Manatools at end included all possibility ideas or snap in/plugin from drakconf ... there with can you only win, if you make snapins with different distributions-scripts, therewith can you are only win, to give the possibility to helping and maintain the manatools and make the way open to use in any Distribution.
Manatools it is a really good thing, maybe it is possible to take the Draktools snapins and make this as a mcc for all distributions , how ever, something like adopt the "mcc" idea it's a really good idea.. and i be behind it of the doing what you are do..  (i know, my english is terrible \*s\* but at least I can communicate )

so, again, yes, a samba-configurations tool like them of draktools is need... as one of the first Configurations snap in's/plugins .. 

best regards
Blacky
